Rework how palette is defined
ColinDuquesnoy/QDarkStyleSheet pull request #253
Opened 2020-12-31 04:30 UTC by isabela-pf

As mentioned in #252, the Spyder team has been working on [updating the default dark and light themes in Spyder](https://github.com/spyder-ide/ux-improvements/issues/13), some of which is based on QDarkStyle. We wanted to give back our relevant work of restructuring how colors develop the palette, and this PR starts that process.

Here's what is changed in this PR:
- palette.py becomes darkpalette.py (anticipating the need for a lightpalette.py in the future). darkpalette.py is now linked to colorsystem.py to define the pre-existing constants.
- Adds colorsystem.py, a file that lists a full range of grays and blues (similar to current QDarkStyle) as a foundation for the initial palette and to support more flexible palette changes in the future.
- Adds colorreference.md in the docs to provide some context for these changes. The color samples folder holds the images used in these docs.

From the user side, the palette should still look about the same.

This type of work is not something I have a lot of experience with, so please forgive any errors. I'm absolutely open to changes.

I can't thank @ccordoba12 enough for helping me structure and correct this PR!

2021-01-04 22:57 UTC, dpizetta requested changes
Hi @isabela-pf, we have converted all the docs of this project to RST format, so we can add more things like tables what is missing in MD format. So, I think would be a good idea to keep this doc as RST too, if you don't mind. You can run the text on a website/tool to convert it.  Tks

2021-01-04 23:11 UTC, dpizetta requested changes

2021-01-04 23:11 UTC, dpizetta commented on qdarkstyle/palette.py
> +    COLOR_SELECTION_DARK = '#14506E'"""
@isabela-pf  you can go ahead and remove those colors as comments, so we have a clean code. :)

2021-01-07 22:46 UTC, isabela-pf commented
Thanks for the feedback! I think I did everything you asked in the last commit, but let me know if there's anything else. 

(Also thanks to @steff456 for troubleshooting my git adventures this time!)

2021-01-08 03:22 UTC, ccordoba12 reviewed
Great work @isabela-pf! I think this is ready, except for my comment below.

> I can't thank @ccordoba12 enough for helping me structure and correct this PR!

Thanks for your kind words! I think you got it almost right yourself, except for some minor details.

2021-01-08 03:22 UTC, ccordoba12 commented on qdarkstyle/darkpalette.py
> +    COLOR_SELECTION_LIGHT = Blue.B60`
You left a back tick at the end of this line. Please remove it.

2021-01-08 21:08 UTC, isabela-pf commented
Back tick removed Thanks for catching that!

2021-01-09 04:13 UTC, ccordoba12 approved these changes
Thanks @isabela-pf, this looks good to me now.

2021-01-09 04:14 UTC, ccordoba12 commented
@dpizetta, what do you think?

2021-01-15 23:04 UTC, ccordoba12 commented
Pinging @dpizetta again. I hope to hear from you soon, else I'll go ahead and merge.

2021-01-17 17:51 UTC, dpizetta commented
Sorry guys, busy days.

I will make some changes to fix some problems when I run the process to generate all the resources, I do the merge in my machine until today night. As the process of generating those resources is not automatized yet, I would recommend we use the develop branch to PR's, so we can keep the fully functional code in the master (for Python and C++). 

Thanks for both

2021-01-17 18:08 UTC, dpizetta commented
The old and new palette for dark theme after the compilation.

![image](https://user-images.githubusercontent.com/5084939/104851777-c7e6c480-58d5-11eb-9bfd-c545d618454a.png)

2021-01-17 18:12 UTC, dpizetta approved these changes

2021-01-17 18:31 UTC, dpizetta commented
Merge done 👍

2021-01-17 18:31 UTC, closed without merging

2021-01-18 15:48 UTC, isabela-pf commented
Thank you so much! ❤️

2021-01-18 15:54 UTC, ccordoba12 commented
Thanks @dpizetta!